# Generated by Django 3.2.6 on 2021-08-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
