# Generated by Django 3.2.6 on 2021-08-14 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210814_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 14, 22, 2, 14, 775703)),
        ),
    ]
